from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(527, 629)
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(20, 90, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.lineEdit_rst = QtWidgets.QLineEdit(Form)
        self.lineEdit_rst.setGeometry(QtCore.QRect(20, 10, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lineEdit_rst.setFont(font)
        self.lineEdit_rst.setObjectName("lineEdit_rst")
        self.pushButton_link = QtWidgets.QPushButton(Form)
        self.pushButton_link.setGeometry(QtCore.QRect(150, 90, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_link.setFont(font)
        self.pushButton_link.setCheckable(False)
        self.pushButton_link.setObjectName("pushButton_link")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 200, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(280, 200, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 200, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_divide = QtWidgets.QPushButton(Form)
        self.pushButton_divide.setGeometry(QtCore.QRect(410, 200, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_multiply = QtWidgets.QPushButton(Form)
        self.pushButton_multiply.setGeometry(QtCore.QRect(410, 310, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 310, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 310, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 310, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 430, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 430, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_minus = QtWidgets.QPushButton(Form)
        self.pushButton_minus.setGeometry(QtCore.QRect(410, 430, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 430, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_dot = QtWidgets.QPushButton(Form)
        self.pushButton_dot.setGeometry(QtCore.QRect(150, 530, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_0 = QtWidgets.QPushButton(Form)
        self.pushButton_0.setGeometry(QtCore.QRect(20, 530, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_plus = QtWidgets.QPushButton(Form)
        self.pushButton_plus.setGeometry(QtCore.QRect(410, 530, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_rst = QtWidgets.QPushButton(Form)
        self.pushButton_rst.setGeometry(QtCore.QRect(280, 530, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_rst.setFont(font)
        self.pushButton_rst.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_rst.setObjectName("pushButton_rst")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "精品计算器"))
        self.pushButton_clear.setText(_translate("Form", "AC"))
        self.pushButton_link.setText(_translate("Form", "www.birdpython.com"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_divide.setText(_translate("Form", "÷"))
        self.pushButton_multiply.setText(_translate("Form", "×"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_dot.setText(_translate("Form", "."))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_rst.setText(_translate("Form", "="))
