version: '3'
services:
  mysql:
    image: docker.io/library/mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=lqs
      - MYSQL_PASSWORD=lqs
      - MYSQL_ROOT_PASSWORD=lqs
    volumes:
      - ./mysqldata:/var/lib/mysql:Z
      - ./mysqlconf:/etc/mysql/conf.d
