version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    command:
      - -c logging_collector=on
    volumes:
      - ./postgresql:/var/lib/postgresql:Z
    ports:
      - "5432:5432"
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=test_db
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=replpass
      - POSTGRES_HOST_AUTH_METHOD=trust
