version: '3'
services:
  registry:
    restart: always
    image: mirrors.sangfor.org/registry:2
    depends_on:
      - server
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/server.key
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=http://localhost:7000/api/artifacts/repository/token
      - REGISTRY_AUTH_TOKEN_SERVICE=artifacts
      - REGISTRY_AUTH_TOKEN_ISSUER=artifacts
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/server.crt
    volumes:
      - ./certs:/certs