apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxypool-Redis
  name: proxypool-Redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: proxypool-Redis